services:
  app:
    build: .
    restart: always
    ports:
      - '3001:3000'
    volumes:
      - ./:/app:z
      - /app/node_modules
      - ./data:/app/data:z
    environment:
      - NODE_ENV=development
    command: ["bun", "src/index.ts"]
